Fix Test deployment job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -88,6 +88,10 @@ jobs:
 
     - name: Test deployment
       run: |
-        DEPLOY_URL=$(gcloud run services describe app2 --platform=managed --region=us-west1 | grep https)
-        echo "Deployment URL: $DEPLOY_URL"
-        curl -sL --max-time 300 -o /dev/null -w "%{http_code}" $DEPLOY_URL | grep 200 || exit 1
+          DEPLOY_URL=$(gcloud run services describe ${{ env.APPLICATION_NAME }} --platform=managed --region=${{ secrets.GCP_REGION }} --format="value(status.url)")
+          echo "Deployment URL: $DEPLOY_URL"
+          if [[ -z "$DEPLOY_URL" ]]; then
+            echo "Error: Deployment URL not found."
+            exit 1
+          fi
+          curl -sL --max-time 300 -o /dev/null -w "%{http_code}" "$DEPLOY_URL" | grep 200 || exit 1
